=begin
#UnifAPI

#Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.

The version of the OpenAPI document: 0.0.1
Contact: support@unifapi.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module Unifapi
  class GeoMentionRecord
    attr_accessor :engine

    attr_accessor :model

    attr_accessor :question

    # Model answer in markdown. Included for standard and full views.
    attr_accessor :answer

    attr_accessor :ai_search_volume

    attr_accessor :monthly_searches

    attr_accessor :sources

    attr_accessor :search_results

    attr_accessor :brand_entities

    attr_accessor :fan_out_queries

    attr_accessor :first_response_at

    attr_accessor :last_response_at

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'engine' => :'engine',
        :'model' => :'model',
        :'question' => :'question',
        :'answer' => :'answer',
        :'ai_search_volume' => :'ai_search_volume',
        :'monthly_searches' => :'monthly_searches',
        :'sources' => :'sources',
        :'search_results' => :'search_results',
        :'brand_entities' => :'brand_entities',
        :'fan_out_queries' => :'fan_out_queries',
        :'first_response_at' => :'first_response_at',
        :'last_response_at' => :'last_response_at'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'engine' => :'GeoEngine',
        :'model' => :'String',
        :'question' => :'String',
        :'answer' => :'String',
        :'ai_search_volume' => :'Float',
        :'monthly_searches' => :'Array<GeoMentionMonthly>',
        :'sources' => :'Array<GeoMentionSource>',
        :'search_results' => :'Array<GeoMentionSearchResult>',
        :'brand_entities' => :'Array<GeoMentionBrandEntity>',
        :'fan_out_queries' => :'Array<String>',
        :'first_response_at' => :'String',
        :'last_response_at' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Unifapi::GeoMentionRecord` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Unifapi::GeoMentionRecord`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'engine')
        self.engine = attributes[:'engine']
      end

      if attributes.key?(:'model')
        self.model = attributes[:'model']
      end

      if attributes.key?(:'question')
        self.question = attributes[:'question']
      end

      if attributes.key?(:'answer')
        self.answer = attributes[:'answer']
      end

      if attributes.key?(:'ai_search_volume')
        self.ai_search_volume = attributes[:'ai_search_volume']
      end

      if attributes.key?(:'monthly_searches')
        if (value = attributes[:'monthly_searches']).is_a?(Array)
          self.monthly_searches = value
        end
      end

      if attributes.key?(:'sources')
        if (value = attributes[:'sources']).is_a?(Array)
          self.sources = value
        end
      end

      if attributes.key?(:'search_results')
        if (value = attributes[:'search_results']).is_a?(Array)
          self.search_results = value
        end
      end

      if attributes.key?(:'brand_entities')
        if (value = attributes[:'brand_entities']).is_a?(Array)
          self.brand_entities = value
        end
      end

      if attributes.key?(:'fan_out_queries')
        if (value = attributes[:'fan_out_queries']).is_a?(Array)
          self.fan_out_queries = value
        end
      end

      if attributes.key?(:'first_response_at')
        self.first_response_at = attributes[:'first_response_at']
      end

      if attributes.key?(:'last_response_at')
        self.last_response_at = attributes[:'last_response_at']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          engine == o.engine &&
          model == o.model &&
          question == o.question &&
          answer == o.answer &&
          ai_search_volume == o.ai_search_volume &&
          monthly_searches == o.monthly_searches &&
          sources == o.sources &&
          search_results == o.search_results &&
          brand_entities == o.brand_entities &&
          fan_out_queries == o.fan_out_queries &&
          first_response_at == o.first_response_at &&
          last_response_at == o.last_response_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [engine, model, question, answer, ai_search_volume, monthly_searches, sources, search_results, brand_entities, fan_out_queries, first_response_at, last_response_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Unifapi.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
