=begin
#UnifAPI

#Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.

The version of the OpenAPI document: 0.0.1
Contact: support@unifapi.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module Unifapi
  class GeoSerpResponse
    attr_accessor :query

    attr_accessor :location

    attr_accessor :language

    attr_accessor :device

    attr_accessor :surface

    attr_accessor :view

    attr_accessor :observed_at

    attr_accessor :search_url

    attr_accessor :total_results

    attr_accessor :serp_features

    # AI SERP elements returned in source order. Top-level AI overview records are billable; cited references, links, images, and answer sections are returned as context inside each result.
    attr_accessor :results

    attr_accessor :target

    # Domains cited or linked by AI Mode, excluding the optional target domain. Omitted when results are truncated by balance.
    attr_accessor :competitors

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'query' => :'query',
        :'location' => :'location',
        :'language' => :'language',
        :'device' => :'device',
        :'surface' => :'surface',
        :'view' => :'view',
        :'observed_at' => :'observed_at',
        :'search_url' => :'search_url',
        :'total_results' => :'total_results',
        :'serp_features' => :'serp_features',
        :'results' => :'results',
        :'target' => :'target',
        :'competitors' => :'competitors'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'query' => :'String',
        :'location' => :'String',
        :'language' => :'String',
        :'device' => :'String',
        :'surface' => :'String',
        :'view' => :'GeoSerpView',
        :'observed_at' => :'String',
        :'search_url' => :'String',
        :'total_results' => :'Integer',
        :'serp_features' => :'Array<String>',
        :'results' => :'Array<GeoSerpResult>',
        :'target' => :'GeoSerpTarget',
        :'competitors' => :'Array<GeoSerpCompetitor>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Unifapi::GeoSerpResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Unifapi::GeoSerpResponse`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'query')
        self.query = attributes[:'query']
      else
        self.query = nil
      end

      if attributes.key?(:'location')
        self.location = attributes[:'location']
      else
        self.location = nil
      end

      if attributes.key?(:'language')
        self.language = attributes[:'language']
      else
        self.language = nil
      end

      if attributes.key?(:'device')
        self.device = attributes[:'device']
      else
        self.device = nil
      end

      if attributes.key?(:'surface')
        self.surface = attributes[:'surface']
      else
        self.surface = nil
      end

      if attributes.key?(:'view')
        self.view = attributes[:'view']
      else
        self.view = nil
      end

      if attributes.key?(:'observed_at')
        self.observed_at = attributes[:'observed_at']
      end

      if attributes.key?(:'search_url')
        self.search_url = attributes[:'search_url']
      end

      if attributes.key?(:'total_results')
        self.total_results = attributes[:'total_results']
      end

      if attributes.key?(:'serp_features')
        if (value = attributes[:'serp_features']).is_a?(Array)
          self.serp_features = value
        end
      else
        self.serp_features = nil
      end

      if attributes.key?(:'results')
        if (value = attributes[:'results']).is_a?(Array)
          self.results = value
        end
      else
        self.results = nil
      end

      if attributes.key?(:'target')
        self.target = attributes[:'target']
      end

      if attributes.key?(:'competitors')
        if (value = attributes[:'competitors']).is_a?(Array)
          self.competitors = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @query.nil?
        invalid_properties.push('invalid value for "query", query cannot be nil.')
      end

      if @location.nil?
        invalid_properties.push('invalid value for "location", location cannot be nil.')
      end

      if @language.nil?
        invalid_properties.push('invalid value for "language", language cannot be nil.')
      end

      if @device.nil?
        invalid_properties.push('invalid value for "device", device cannot be nil.')
      end

      if @surface.nil?
        invalid_properties.push('invalid value for "surface", surface cannot be nil.')
      end

      if @view.nil?
        invalid_properties.push('invalid value for "view", view cannot be nil.')
      end

      if @serp_features.nil?
        invalid_properties.push('invalid value for "serp_features", serp_features cannot be nil.')
      end

      if @results.nil?
        invalid_properties.push('invalid value for "results", results cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @query.nil?
      return false if @location.nil?
      return false if @language.nil?
      return false if @device.nil?
      device_validator = EnumAttributeValidator.new('String', ["desktop", "mobile"])
      return false unless device_validator.valid?(@device)
      return false if @surface.nil?
      surface_validator = EnumAttributeValidator.new('String', ["google_ai_mode"])
      return false unless surface_validator.valid?(@surface)
      return false if @view.nil?
      return false if @serp_features.nil?
      return false if @results.nil?
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] device Object to be assigned
    def device=(device)
      validator = EnumAttributeValidator.new('String', ["desktop", "mobile"])
      unless validator.valid?(device)
        fail ArgumentError, "invalid value for \"device\", must be one of #{validator.allowable_values}."
      end
      @device = device
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] surface Object to be assigned
    def surface=(surface)
      validator = EnumAttributeValidator.new('String', ["google_ai_mode"])
      unless validator.valid?(surface)
        fail ArgumentError, "invalid value for \"surface\", must be one of #{validator.allowable_values}."
      end
      @surface = surface
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          query == o.query &&
          location == o.location &&
          language == o.language &&
          device == o.device &&
          surface == o.surface &&
          view == o.view &&
          observed_at == o.observed_at &&
          search_url == o.search_url &&
          total_results == o.total_results &&
          serp_features == o.serp_features &&
          results == o.results &&
          target == o.target &&
          competitors == o.competitors
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [query, location, language, device, surface, view, observed_at, search_url, total_results, serp_features, results, target, competitors].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Unifapi.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
