=begin
#UnifAPI

#Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.

The version of the OpenAPI document: 0.0.1
Contact: support@unifapi.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module Unifapi
  class HotelSearchRequest
    # Optional hotel name or search query. Combine with location to scope the search.
    attr_accessor :query

    attr_accessor :location

    # Search language as an ISO code or full language name. Defaults to en.
    attr_accessor :language

    # Number of hotels to return. Defaults to 10.
    attr_accessor :limit

    # Check-in date. Date in YYYY-MM-DD format.
    attr_accessor :check_in

    # Check-out date. Date in YYYY-MM-DD format.
    attr_accessor :check_out

    # ISO 4217 currency code for prices, such as USD.
    attr_accessor :currency

    # Number of adult guests.
    attr_accessor :adults

    # Ages of children staying, used to refine availability and pricing.
    attr_accessor :children

    # Filter to hotels with these class ratings, such as [4, 5].
    attr_accessor :stars

    # Filter to hotels with at least this guest rating.
    attr_accessor :min_rating

    # Sort order for results. Defaults to relevance.
    attr_accessor :sort_by

    # Minimum price per night.
    attr_accessor :min_price

    # Maximum price per night.
    attr_accessor :max_price

    # When true, only return hotels offering free cancellation.
    attr_accessor :free_cancellation

    # When true, search vacation rentals instead of hotels.
    attr_accessor :is_vacation_rentals

    # Filter to hotels offering these amenities, such as pool or free_wifi.
    attr_accessor :amenities

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'query' => :'query',
        :'location' => :'location',
        :'language' => :'language',
        :'limit' => :'limit',
        :'check_in' => :'check_in',
        :'check_out' => :'check_out',
        :'currency' => :'currency',
        :'adults' => :'adults',
        :'children' => :'children',
        :'stars' => :'stars',
        :'min_rating' => :'min_rating',
        :'sort_by' => :'sort_by',
        :'min_price' => :'min_price',
        :'max_price' => :'max_price',
        :'free_cancellation' => :'free_cancellation',
        :'is_vacation_rentals' => :'is_vacation_rentals',
        :'amenities' => :'amenities'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'query' => :'String',
        :'location' => :'HotelSearchLocation',
        :'language' => :'String',
        :'limit' => :'Integer',
        :'check_in' => :'String',
        :'check_out' => :'String',
        :'currency' => :'String',
        :'adults' => :'Integer',
        :'children' => :'Array<Integer>',
        :'stars' => :'Array<Integer>',
        :'min_rating' => :'Float',
        :'sort_by' => :'String',
        :'min_price' => :'Integer',
        :'max_price' => :'Integer',
        :'free_cancellation' => :'Boolean',
        :'is_vacation_rentals' => :'Boolean',
        :'amenities' => :'Array<String>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Unifapi::HotelSearchRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Unifapi::HotelSearchRequest`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'query')
        self.query = attributes[:'query']
      end

      if attributes.key?(:'location')
        self.location = attributes[:'location']
      end

      if attributes.key?(:'language')
        self.language = attributes[:'language']
      end

      if attributes.key?(:'limit')
        self.limit = attributes[:'limit']
      end

      if attributes.key?(:'check_in')
        self.check_in = attributes[:'check_in']
      end

      if attributes.key?(:'check_out')
        self.check_out = attributes[:'check_out']
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      end

      if attributes.key?(:'adults')
        self.adults = attributes[:'adults']
      end

      if attributes.key?(:'children')
        if (value = attributes[:'children']).is_a?(Array)
          self.children = value
        end
      end

      if attributes.key?(:'stars')
        if (value = attributes[:'stars']).is_a?(Array)
          self.stars = value
        end
      end

      if attributes.key?(:'min_rating')
        self.min_rating = attributes[:'min_rating']
      end

      if attributes.key?(:'sort_by')
        self.sort_by = attributes[:'sort_by']
      end

      if attributes.key?(:'min_price')
        self.min_price = attributes[:'min_price']
      end

      if attributes.key?(:'max_price')
        self.max_price = attributes[:'max_price']
      end

      if attributes.key?(:'free_cancellation')
        self.free_cancellation = attributes[:'free_cancellation']
      end

      if attributes.key?(:'is_vacation_rentals')
        self.is_vacation_rentals = attributes[:'is_vacation_rentals']
      end

      if attributes.key?(:'amenities')
        if (value = attributes[:'amenities']).is_a?(Array)
          self.amenities = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@query.nil? && @query.to_s.length > 700
        invalid_properties.push('invalid value for "query", the character length must be smaller than or equal to 700.')
      end

      if !@query.nil? && @query.to_s.length < 1
        invalid_properties.push('invalid value for "query", the character length must be great than or equal to 1.')
      end

      if !@language.nil? && @language.to_s.length > 80
        invalid_properties.push('invalid value for "language", the character length must be smaller than or equal to 80.')
      end

      if !@language.nil? && @language.to_s.length < 2
        invalid_properties.push('invalid value for "language", the character length must be great than or equal to 2.')
      end

      if !@limit.nil? && @limit > 100
        invalid_properties.push('invalid value for "limit", must be smaller than or equal to 100.')
      end

      if !@limit.nil? && @limit < 1
        invalid_properties.push('invalid value for "limit", must be greater than or equal to 1.')
      end

      pattern = Regexp.new(/^\d{4}-\d{2}-\d{2}$/)
      if !@check_in.nil? && @check_in !~ pattern
        invalid_properties.push("invalid value for \"check_in\", must conform to the pattern #{pattern}.")
      end

      pattern = Regexp.new(/^\d{4}-\d{2}-\d{2}$/)
      if !@check_out.nil? && @check_out !~ pattern
        invalid_properties.push("invalid value for \"check_out\", must conform to the pattern #{pattern}.")
      end

      if !@currency.nil? && @currency.to_s.length > 3
        invalid_properties.push('invalid value for "currency", the character length must be smaller than or equal to 3.')
      end

      if !@currency.nil? && @currency.to_s.length < 3
        invalid_properties.push('invalid value for "currency", the character length must be great than or equal to 3.')
      end

      if !@adults.nil? && @adults > 30
        invalid_properties.push('invalid value for "adults", must be smaller than or equal to 30.')
      end

      if !@adults.nil? && @adults < 1
        invalid_properties.push('invalid value for "adults", must be greater than or equal to 1.')
      end

      if !@children.nil? && @children.length > 10
        invalid_properties.push('invalid value for "children", number of items must be less than or equal to 10.')
      end

      if !@stars.nil? && @stars.length > 5
        invalid_properties.push('invalid value for "stars", number of items must be less than or equal to 5.')
      end

      if !@min_rating.nil? && @min_rating > 5
        invalid_properties.push('invalid value for "min_rating", must be smaller than or equal to 5.')
      end

      if !@min_rating.nil? && @min_rating < 0
        invalid_properties.push('invalid value for "min_rating", must be greater than or equal to 0.')
      end

      if !@min_price.nil? && @min_price < 0
        invalid_properties.push('invalid value for "min_price", must be greater than or equal to 0.')
      end

      if !@max_price.nil? && @max_price < 0
        invalid_properties.push('invalid value for "max_price", must be greater than or equal to 0.')
      end

      if !@amenities.nil? && @amenities.length > 30
        invalid_properties.push('invalid value for "amenities", number of items must be less than or equal to 30.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@query.nil? && @query.to_s.length > 700
      return false if !@query.nil? && @query.to_s.length < 1
      return false if !@language.nil? && @language.to_s.length > 80
      return false if !@language.nil? && @language.to_s.length < 2
      return false if !@limit.nil? && @limit > 100
      return false if !@limit.nil? && @limit < 1
      return false if !@check_in.nil? && @check_in !~ Regexp.new(/^\d{4}-\d{2}-\d{2}$/)
      return false if !@check_out.nil? && @check_out !~ Regexp.new(/^\d{4}-\d{2}-\d{2}$/)
      return false if !@currency.nil? && @currency.to_s.length > 3
      return false if !@currency.nil? && @currency.to_s.length < 3
      return false if !@adults.nil? && @adults > 30
      return false if !@adults.nil? && @adults < 1
      return false if !@children.nil? && @children.length > 10
      return false if !@stars.nil? && @stars.length > 5
      return false if !@min_rating.nil? && @min_rating > 5
      return false if !@min_rating.nil? && @min_rating < 0
      sort_by_validator = EnumAttributeValidator.new('String', ["relevance", "lowest_price", "highest_rating", "most_reviewed"])
      return false unless sort_by_validator.valid?(@sort_by)
      return false if !@min_price.nil? && @min_price < 0
      return false if !@max_price.nil? && @max_price < 0
      return false if !@amenities.nil? && @amenities.length > 30
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] query Value to be assigned
    def query=(query)
      if query.nil?
        fail ArgumentError, 'query cannot be nil'
      end

      if query.to_s.length > 700
        fail ArgumentError, 'invalid value for "query", the character length must be smaller than or equal to 700.'
      end

      if query.to_s.length < 1
        fail ArgumentError, 'invalid value for "query", the character length must be great than or equal to 1.'
      end

      @query = query
    end

    # Custom attribute writer method with validation
    # @param [Object] language Value to be assigned
    def language=(language)
      if language.nil?
        fail ArgumentError, 'language cannot be nil'
      end

      if language.to_s.length > 80
        fail ArgumentError, 'invalid value for "language", the character length must be smaller than or equal to 80.'
      end

      if language.to_s.length < 2
        fail ArgumentError, 'invalid value for "language", the character length must be great than or equal to 2.'
      end

      @language = language
    end

    # Custom attribute writer method with validation
    # @param [Object] limit Value to be assigned
    def limit=(limit)
      if limit.nil?
        fail ArgumentError, 'limit cannot be nil'
      end

      if limit > 100
        fail ArgumentError, 'invalid value for "limit", must be smaller than or equal to 100.'
      end

      if limit < 1
        fail ArgumentError, 'invalid value for "limit", must be greater than or equal to 1.'
      end

      @limit = limit
    end

    # Custom attribute writer method with validation
    # @param [Object] check_in Value to be assigned
    def check_in=(check_in)
      if check_in.nil?
        fail ArgumentError, 'check_in cannot be nil'
      end

      pattern = Regexp.new(/^\d{4}-\d{2}-\d{2}$/)
      if check_in !~ pattern
        fail ArgumentError, "invalid value for \"check_in\", must conform to the pattern #{pattern}."
      end

      @check_in = check_in
    end

    # Custom attribute writer method with validation
    # @param [Object] check_out Value to be assigned
    def check_out=(check_out)
      if check_out.nil?
        fail ArgumentError, 'check_out cannot be nil'
      end

      pattern = Regexp.new(/^\d{4}-\d{2}-\d{2}$/)
      if check_out !~ pattern
        fail ArgumentError, "invalid value for \"check_out\", must conform to the pattern #{pattern}."
      end

      @check_out = check_out
    end

    # Custom attribute writer method with validation
    # @param [Object] currency Value to be assigned
    def currency=(currency)
      if currency.nil?
        fail ArgumentError, 'currency cannot be nil'
      end

      if currency.to_s.length > 3
        fail ArgumentError, 'invalid value for "currency", the character length must be smaller than or equal to 3.'
      end

      if currency.to_s.length < 3
        fail ArgumentError, 'invalid value for "currency", the character length must be great than or equal to 3.'
      end

      @currency = currency
    end

    # Custom attribute writer method with validation
    # @param [Object] adults Value to be assigned
    def adults=(adults)
      if adults.nil?
        fail ArgumentError, 'adults cannot be nil'
      end

      if adults > 30
        fail ArgumentError, 'invalid value for "adults", must be smaller than or equal to 30.'
      end

      if adults < 1
        fail ArgumentError, 'invalid value for "adults", must be greater than or equal to 1.'
      end

      @adults = adults
    end

    # Custom attribute writer method with validation
    # @param [Object] children Value to be assigned
    def children=(children)
      if children.nil?
        fail ArgumentError, 'children cannot be nil'
      end

      if children.length > 10
        fail ArgumentError, 'invalid value for "children", number of items must be less than or equal to 10.'
      end

      @children = children
    end

    # Custom attribute writer method with validation
    # @param [Object] stars Value to be assigned
    def stars=(stars)
      if stars.nil?
        fail ArgumentError, 'stars cannot be nil'
      end

      if stars.length > 5
        fail ArgumentError, 'invalid value for "stars", number of items must be less than or equal to 5.'
      end

      @stars = stars
    end

    # Custom attribute writer method with validation
    # @param [Object] min_rating Value to be assigned
    def min_rating=(min_rating)
      if min_rating.nil?
        fail ArgumentError, 'min_rating cannot be nil'
      end

      if min_rating > 5
        fail ArgumentError, 'invalid value for "min_rating", must be smaller than or equal to 5.'
      end

      if min_rating < 0
        fail ArgumentError, 'invalid value for "min_rating", must be greater than or equal to 0.'
      end

      @min_rating = min_rating
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] sort_by Object to be assigned
    def sort_by=(sort_by)
      validator = EnumAttributeValidator.new('String', ["relevance", "lowest_price", "highest_rating", "most_reviewed"])
      unless validator.valid?(sort_by)
        fail ArgumentError, "invalid value for \"sort_by\", must be one of #{validator.allowable_values}."
      end
      @sort_by = sort_by
    end

    # Custom attribute writer method with validation
    # @param [Object] min_price Value to be assigned
    def min_price=(min_price)
      if min_price.nil?
        fail ArgumentError, 'min_price cannot be nil'
      end

      if min_price < 0
        fail ArgumentError, 'invalid value for "min_price", must be greater than or equal to 0.'
      end

      @min_price = min_price
    end

    # Custom attribute writer method with validation
    # @param [Object] max_price Value to be assigned
    def max_price=(max_price)
      if max_price.nil?
        fail ArgumentError, 'max_price cannot be nil'
      end

      if max_price < 0
        fail ArgumentError, 'invalid value for "max_price", must be greater than or equal to 0.'
      end

      @max_price = max_price
    end

    # Custom attribute writer method with validation
    # @param [Object] amenities Value to be assigned
    def amenities=(amenities)
      if amenities.nil?
        fail ArgumentError, 'amenities cannot be nil'
      end

      if amenities.length > 30
        fail ArgumentError, 'invalid value for "amenities", number of items must be less than or equal to 30.'
      end

      @amenities = amenities
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          query == o.query &&
          location == o.location &&
          language == o.language &&
          limit == o.limit &&
          check_in == o.check_in &&
          check_out == o.check_out &&
          currency == o.currency &&
          adults == o.adults &&
          children == o.children &&
          stars == o.stars &&
          min_rating == o.min_rating &&
          sort_by == o.sort_by &&
          min_price == o.min_price &&
          max_price == o.max_price &&
          free_cancellation == o.free_cancellation &&
          is_vacation_rentals == o.is_vacation_rentals &&
          amenities == o.amenities
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [query, location, language, limit, check_in, check_out, currency, adults, children, stars, min_rating, sort_by, min_price, max_price, free_cancellation, is_vacation_rentals, amenities].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Unifapi.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
