=begin
#UnifAPI

#Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.

The version of the OpenAPI document: 0.0.1
Contact: support@unifapi.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module Unifapi
  class SeoRelatedKeywordsRequest
    # Seed keyword. Returns keywords from Google's 'searches related to' element.
    attr_accessor :keyword

    attr_accessor :location

    # Search language as an ISO code or full language name. Defaults to en.
    attr_accessor :language

    # Keyword search depth, 0-4. Higher depth returns more keywords (1≈8, 2≈72, 3≈584, 4≈4680). Defaults to 1.
    attr_accessor :depth

    # Maximum number of related keywords to return. Defaults to 100.
    attr_accessor :limit

    # Number of related keywords to skip from the start of the results.
    attr_accessor :offset

    # When true, exclude highly similar keywords and return only core keywords.
    attr_accessor :ignore_synonyms

    # When true, include SERP data (result count and SERP feature types) for each keyword. Can add source cost.
    attr_accessor :include_serp_info

    # When true, include metrics for the seed keyword in the response.
    attr_accessor :include_seed_keyword

    attr_accessor :view

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'keyword' => :'keyword',
        :'location' => :'location',
        :'language' => :'language',
        :'depth' => :'depth',
        :'limit' => :'limit',
        :'offset' => :'offset',
        :'ignore_synonyms' => :'ignore_synonyms',
        :'include_serp_info' => :'include_serp_info',
        :'include_seed_keyword' => :'include_seed_keyword',
        :'view' => :'view'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'keyword' => :'String',
        :'location' => :'SeoRelatedKeywordsLocation',
        :'language' => :'String',
        :'depth' => :'Integer',
        :'limit' => :'Integer',
        :'offset' => :'Integer',
        :'ignore_synonyms' => :'Boolean',
        :'include_serp_info' => :'Boolean',
        :'include_seed_keyword' => :'Boolean',
        :'view' => :'SeoKeywordView'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Unifapi::SeoRelatedKeywordsRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Unifapi::SeoRelatedKeywordsRequest`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'keyword')
        self.keyword = attributes[:'keyword']
      else
        self.keyword = nil
      end

      if attributes.key?(:'location')
        self.location = attributes[:'location']
      end

      if attributes.key?(:'language')
        self.language = attributes[:'language']
      end

      if attributes.key?(:'depth')
        self.depth = attributes[:'depth']
      end

      if attributes.key?(:'limit')
        self.limit = attributes[:'limit']
      end

      if attributes.key?(:'offset')
        self.offset = attributes[:'offset']
      end

      if attributes.key?(:'ignore_synonyms')
        self.ignore_synonyms = attributes[:'ignore_synonyms']
      end

      if attributes.key?(:'include_serp_info')
        self.include_serp_info = attributes[:'include_serp_info']
      end

      if attributes.key?(:'include_seed_keyword')
        self.include_seed_keyword = attributes[:'include_seed_keyword']
      end

      if attributes.key?(:'view')
        self.view = attributes[:'view']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @keyword.nil?
        invalid_properties.push('invalid value for "keyword", keyword cannot be nil.')
      end

      if @keyword.to_s.length > 80
        invalid_properties.push('invalid value for "keyword", the character length must be smaller than or equal to 80.')
      end

      if @keyword.to_s.length < 1
        invalid_properties.push('invalid value for "keyword", the character length must be great than or equal to 1.')
      end

      if !@language.nil? && @language.to_s.length > 80
        invalid_properties.push('invalid value for "language", the character length must be smaller than or equal to 80.')
      end

      if !@language.nil? && @language.to_s.length < 2
        invalid_properties.push('invalid value for "language", the character length must be great than or equal to 2.')
      end

      if !@depth.nil? && @depth > 4
        invalid_properties.push('invalid value for "depth", must be smaller than or equal to 4.')
      end

      if !@depth.nil? && @depth < 0
        invalid_properties.push('invalid value for "depth", must be greater than or equal to 0.')
      end

      if !@limit.nil? && @limit > 1000
        invalid_properties.push('invalid value for "limit", must be smaller than or equal to 1000.')
      end

      if !@limit.nil? && @limit < 1
        invalid_properties.push('invalid value for "limit", must be greater than or equal to 1.')
      end

      if !@offset.nil? && @offset < 0
        invalid_properties.push('invalid value for "offset", must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @keyword.nil?
      return false if @keyword.to_s.length > 80
      return false if @keyword.to_s.length < 1
      return false if !@language.nil? && @language.to_s.length > 80
      return false if !@language.nil? && @language.to_s.length < 2
      return false if !@depth.nil? && @depth > 4
      return false if !@depth.nil? && @depth < 0
      return false if !@limit.nil? && @limit > 1000
      return false if !@limit.nil? && @limit < 1
      return false if !@offset.nil? && @offset < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] keyword Value to be assigned
    def keyword=(keyword)
      if keyword.nil?
        fail ArgumentError, 'keyword cannot be nil'
      end

      if keyword.to_s.length > 80
        fail ArgumentError, 'invalid value for "keyword", the character length must be smaller than or equal to 80.'
      end

      if keyword.to_s.length < 1
        fail ArgumentError, 'invalid value for "keyword", the character length must be great than or equal to 1.'
      end

      @keyword = keyword
    end

    # Custom attribute writer method with validation
    # @param [Object] language Value to be assigned
    def language=(language)
      if language.nil?
        fail ArgumentError, 'language cannot be nil'
      end

      if language.to_s.length > 80
        fail ArgumentError, 'invalid value for "language", the character length must be smaller than or equal to 80.'
      end

      if language.to_s.length < 2
        fail ArgumentError, 'invalid value for "language", the character length must be great than or equal to 2.'
      end

      @language = language
    end

    # Custom attribute writer method with validation
    # @param [Object] depth Value to be assigned
    def depth=(depth)
      if depth.nil?
        fail ArgumentError, 'depth cannot be nil'
      end

      if depth > 4
        fail ArgumentError, 'invalid value for "depth", must be smaller than or equal to 4.'
      end

      if depth < 0
        fail ArgumentError, 'invalid value for "depth", must be greater than or equal to 0.'
      end

      @depth = depth
    end

    # Custom attribute writer method with validation
    # @param [Object] limit Value to be assigned
    def limit=(limit)
      if limit.nil?
        fail ArgumentError, 'limit cannot be nil'
      end

      if limit > 1000
        fail ArgumentError, 'invalid value for "limit", must be smaller than or equal to 1000.'
      end

      if limit < 1
        fail ArgumentError, 'invalid value for "limit", must be greater than or equal to 1.'
      end

      @limit = limit
    end

    # Custom attribute writer method with validation
    # @param [Object] offset Value to be assigned
    def offset=(offset)
      if offset.nil?
        fail ArgumentError, 'offset cannot be nil'
      end

      if offset < 0
        fail ArgumentError, 'invalid value for "offset", must be greater than or equal to 0.'
      end

      @offset = offset
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          keyword == o.keyword &&
          location == o.location &&
          language == o.language &&
          depth == o.depth &&
          limit == o.limit &&
          offset == o.offset &&
          ignore_synonyms == o.ignore_synonyms &&
          include_serp_info == o.include_serp_info &&
          include_seed_keyword == o.include_seed_keyword &&
          view == o.view
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [keyword, location, language, depth, limit, offset, ignore_synonyms, include_serp_info, include_seed_keyword, view].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Unifapi.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
