=begin
#UnifAPI

#Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.

The version of the OpenAPI document: 0.0.1
Contact: support@unifapi.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module Unifapi
  class SeoKeywordView
    SUMMARY = "summary".freeze
    STANDARD = "standard".freeze
    FULL = "full".freeze

    def self.all_vars
      @all_vars ||= [SUMMARY, STANDARD, FULL].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if SeoKeywordView.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #SeoKeywordView"
    end
  end
end
