=begin
#UnifAPI

#Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.

The version of the OpenAPI document: 0.0.1
Contact: support@unifapi.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module Unifapi
  class SeoDomainIntersectionRequest
    # First domain, such as example.com.
    attr_accessor :target1

    # Second domain to compare against.
    attr_accessor :target2

    attr_accessor :location

    # Search language as an ISO code or full language name. Defaults to en.
    attr_accessor :language

    # When true (default), return keywords both domains rank for. When false, return keywords the first domain ranks for but the second does not.
    attr_accessor :intersections

    # Maximum number of keywords to return. Defaults to 100.
    attr_accessor :limit

    # Number of keywords to skip from the start of the results.
    attr_accessor :offset

    attr_accessor :view

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'target1' => :'target1',
        :'target2' => :'target2',
        :'location' => :'location',
        :'language' => :'language',
        :'intersections' => :'intersections',
        :'limit' => :'limit',
        :'offset' => :'offset',
        :'view' => :'view'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'target1' => :'String',
        :'target2' => :'String',
        :'location' => :'SeoDomainIntersectionLocation',
        :'language' => :'String',
        :'intersections' => :'Boolean',
        :'limit' => :'Integer',
        :'offset' => :'Integer',
        :'view' => :'SeoKeywordView'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Unifapi::SeoDomainIntersectionRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Unifapi::SeoDomainIntersectionRequest`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'target1')
        self.target1 = attributes[:'target1']
      else
        self.target1 = nil
      end

      if attributes.key?(:'target2')
        self.target2 = attributes[:'target2']
      else
        self.target2 = nil
      end

      if attributes.key?(:'location')
        self.location = attributes[:'location']
      end

      if attributes.key?(:'language')
        self.language = attributes[:'language']
      end

      if attributes.key?(:'intersections')
        self.intersections = attributes[:'intersections']
      end

      if attributes.key?(:'limit')
        self.limit = attributes[:'limit']
      end

      if attributes.key?(:'offset')
        self.offset = attributes[:'offset']
      end

      if attributes.key?(:'view')
        self.view = attributes[:'view']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @target1.nil?
        invalid_properties.push('invalid value for "target1", target1 cannot be nil.')
      end

      if @target1.to_s.length > 253
        invalid_properties.push('invalid value for "target1", the character length must be smaller than or equal to 253.')
      end

      if @target1.to_s.length < 1
        invalid_properties.push('invalid value for "target1", the character length must be great than or equal to 1.')
      end

      if @target2.nil?
        invalid_properties.push('invalid value for "target2", target2 cannot be nil.')
      end

      if @target2.to_s.length > 253
        invalid_properties.push('invalid value for "target2", the character length must be smaller than or equal to 253.')
      end

      if @target2.to_s.length < 1
        invalid_properties.push('invalid value for "target2", the character length must be great than or equal to 1.')
      end

      if !@language.nil? && @language.to_s.length > 80
        invalid_properties.push('invalid value for "language", the character length must be smaller than or equal to 80.')
      end

      if !@language.nil? && @language.to_s.length < 2
        invalid_properties.push('invalid value for "language", the character length must be great than or equal to 2.')
      end

      if !@limit.nil? && @limit > 1000
        invalid_properties.push('invalid value for "limit", must be smaller than or equal to 1000.')
      end

      if !@limit.nil? && @limit < 1
        invalid_properties.push('invalid value for "limit", must be greater than or equal to 1.')
      end

      if !@offset.nil? && @offset < 0
        invalid_properties.push('invalid value for "offset", must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @target1.nil?
      return false if @target1.to_s.length > 253
      return false if @target1.to_s.length < 1
      return false if @target2.nil?
      return false if @target2.to_s.length > 253
      return false if @target2.to_s.length < 1
      return false if !@language.nil? && @language.to_s.length > 80
      return false if !@language.nil? && @language.to_s.length < 2
      return false if !@limit.nil? && @limit > 1000
      return false if !@limit.nil? && @limit < 1
      return false if !@offset.nil? && @offset < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] target1 Value to be assigned
    def target1=(target1)
      if target1.nil?
        fail ArgumentError, 'target1 cannot be nil'
      end

      if target1.to_s.length > 253
        fail ArgumentError, 'invalid value for "target1", the character length must be smaller than or equal to 253.'
      end

      if target1.to_s.length < 1
        fail ArgumentError, 'invalid value for "target1", the character length must be great than or equal to 1.'
      end

      @target1 = target1
    end

    # Custom attribute writer method with validation
    # @param [Object] target2 Value to be assigned
    def target2=(target2)
      if target2.nil?
        fail ArgumentError, 'target2 cannot be nil'
      end

      if target2.to_s.length > 253
        fail ArgumentError, 'invalid value for "target2", the character length must be smaller than or equal to 253.'
      end

      if target2.to_s.length < 1
        fail ArgumentError, 'invalid value for "target2", the character length must be great than or equal to 1.'
      end

      @target2 = target2
    end

    # Custom attribute writer method with validation
    # @param [Object] language Value to be assigned
    def language=(language)
      if language.nil?
        fail ArgumentError, 'language cannot be nil'
      end

      if language.to_s.length > 80
        fail ArgumentError, 'invalid value for "language", the character length must be smaller than or equal to 80.'
      end

      if language.to_s.length < 2
        fail ArgumentError, 'invalid value for "language", the character length must be great than or equal to 2.'
      end

      @language = language
    end

    # Custom attribute writer method with validation
    # @param [Object] limit Value to be assigned
    def limit=(limit)
      if limit.nil?
        fail ArgumentError, 'limit cannot be nil'
      end

      if limit > 1000
        fail ArgumentError, 'invalid value for "limit", must be smaller than or equal to 1000.'
      end

      if limit < 1
        fail ArgumentError, 'invalid value for "limit", must be greater than or equal to 1.'
      end

      @limit = limit
    end

    # Custom attribute writer method with validation
    # @param [Object] offset Value to be assigned
    def offset=(offset)
      if offset.nil?
        fail ArgumentError, 'offset cannot be nil'
      end

      if offset < 0
        fail ArgumentError, 'invalid value for "offset", must be greater than or equal to 0.'
      end

      @offset = offset
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          target1 == o.target1 &&
          target2 == o.target2 &&
          location == o.location &&
          language == o.language &&
          intersections == o.intersections &&
          limit == o.limit &&
          offset == o.offset &&
          view == o.view
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [target1, target2, location, language, intersections, limit, offset, view].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Unifapi.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
