=begin
#UnifAPI

#Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.

The version of the OpenAPI document: 0.0.1
Contact: support@unifapi.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module Unifapi
  class SeoRelatedKeywordItem
    # Keyword phrase.
    attr_accessor :keyword

    # Average monthly Google search volume.
    attr_accessor :search_volume

    # Average cost-per-click in USD.
    attr_accessor :cpc

    # Google Ads competition index between 0 and 1.
    attr_accessor :competition

    # Google Ads competition level: LOW, MEDIUM, or HIGH.
    attr_accessor :competition_level

    # Relative difficulty of ranking in the top-10 organic results, 0-100.
    attr_accessor :keyword_difficulty

    # Main search intent: informational, navigational, commercial, or transactional.
    attr_accessor :search_intent

    # Supplementary search intents detected for the keyword.
    attr_accessor :search_intent_alternatives

    # Lower-range top-of-page bid in USD from Google Ads.
    attr_accessor :low_top_of_page_bid

    # Upper-range top-of-page bid in USD from Google Ads.
    attr_accessor :high_top_of_page_bid

    # Number of words in the keyword.
    attr_accessor :words_count

    # Language detected for the keyword.
    attr_accessor :detected_language

    attr_accessor :search_volume_trend

    # SERP feature types present for the keyword (only with include_serp_info).
    attr_accessor :serp_item_types

    # Number of organic results Google reports for the keyword.
    attr_accessor :serp_results_count

    # Per-month search volume for the past 12 months (full view only).
    attr_accessor :monthly_searches

    # When DataForSEO last refreshed the keyword metrics.
    attr_accessor :last_updated_at

    # Search depth at which this keyword was found, relative to the seed keyword.
    attr_accessor :depth

    # Keywords from the 'searches related to' SERP element for this keyword.
    attr_accessor :related_keywords

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'keyword' => :'keyword',
        :'search_volume' => :'search_volume',
        :'cpc' => :'cpc',
        :'competition' => :'competition',
        :'competition_level' => :'competition_level',
        :'keyword_difficulty' => :'keyword_difficulty',
        :'search_intent' => :'search_intent',
        :'search_intent_alternatives' => :'search_intent_alternatives',
        :'low_top_of_page_bid' => :'low_top_of_page_bid',
        :'high_top_of_page_bid' => :'high_top_of_page_bid',
        :'words_count' => :'words_count',
        :'detected_language' => :'detected_language',
        :'search_volume_trend' => :'search_volume_trend',
        :'serp_item_types' => :'serp_item_types',
        :'serp_results_count' => :'serp_results_count',
        :'monthly_searches' => :'monthly_searches',
        :'last_updated_at' => :'last_updated_at',
        :'depth' => :'depth',
        :'related_keywords' => :'related_keywords'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'keyword' => :'String',
        :'search_volume' => :'Integer',
        :'cpc' => :'Float',
        :'competition' => :'Float',
        :'competition_level' => :'String',
        :'keyword_difficulty' => :'Integer',
        :'search_intent' => :'String',
        :'search_intent_alternatives' => :'Array<String>',
        :'low_top_of_page_bid' => :'Float',
        :'high_top_of_page_bid' => :'Float',
        :'words_count' => :'Integer',
        :'detected_language' => :'String',
        :'search_volume_trend' => :'SeoKeywordSearchVolumeTrend',
        :'serp_item_types' => :'Array<String>',
        :'serp_results_count' => :'Integer',
        :'monthly_searches' => :'Array<SeoKeywordMonthlySearch>',
        :'last_updated_at' => :'String',
        :'depth' => :'Integer',
        :'related_keywords' => :'Array<String>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # List of class defined in allOf (OpenAPI v3)
    def self.openapi_all_of
      [
      :'SeoKeywordItem'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Unifapi::SeoRelatedKeywordItem` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Unifapi::SeoRelatedKeywordItem`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'keyword')
        self.keyword = attributes[:'keyword']
      else
        self.keyword = nil
      end

      if attributes.key?(:'search_volume')
        self.search_volume = attributes[:'search_volume']
      end

      if attributes.key?(:'cpc')
        self.cpc = attributes[:'cpc']
      end

      if attributes.key?(:'competition')
        self.competition = attributes[:'competition']
      end

      if attributes.key?(:'competition_level')
        self.competition_level = attributes[:'competition_level']
      end

      if attributes.key?(:'keyword_difficulty')
        self.keyword_difficulty = attributes[:'keyword_difficulty']
      end

      if attributes.key?(:'search_intent')
        self.search_intent = attributes[:'search_intent']
      end

      if attributes.key?(:'search_intent_alternatives')
        if (value = attributes[:'search_intent_alternatives']).is_a?(Array)
          self.search_intent_alternatives = value
        end
      end

      if attributes.key?(:'low_top_of_page_bid')
        self.low_top_of_page_bid = attributes[:'low_top_of_page_bid']
      end

      if attributes.key?(:'high_top_of_page_bid')
        self.high_top_of_page_bid = attributes[:'high_top_of_page_bid']
      end

      if attributes.key?(:'words_count')
        self.words_count = attributes[:'words_count']
      end

      if attributes.key?(:'detected_language')
        self.detected_language = attributes[:'detected_language']
      end

      if attributes.key?(:'search_volume_trend')
        self.search_volume_trend = attributes[:'search_volume_trend']
      end

      if attributes.key?(:'serp_item_types')
        if (value = attributes[:'serp_item_types']).is_a?(Array)
          self.serp_item_types = value
        end
      end

      if attributes.key?(:'serp_results_count')
        self.serp_results_count = attributes[:'serp_results_count']
      end

      if attributes.key?(:'monthly_searches')
        if (value = attributes[:'monthly_searches']).is_a?(Array)
          self.monthly_searches = value
        end
      end

      if attributes.key?(:'last_updated_at')
        self.last_updated_at = attributes[:'last_updated_at']
      end

      if attributes.key?(:'depth')
        self.depth = attributes[:'depth']
      end

      if attributes.key?(:'related_keywords')
        if (value = attributes[:'related_keywords']).is_a?(Array)
          self.related_keywords = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @keyword.nil?
        invalid_properties.push('invalid value for "keyword", keyword cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @keyword.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          keyword == o.keyword &&
          search_volume == o.search_volume &&
          cpc == o.cpc &&
          competition == o.competition &&
          competition_level == o.competition_level &&
          keyword_difficulty == o.keyword_difficulty &&
          search_intent == o.search_intent &&
          search_intent_alternatives == o.search_intent_alternatives &&
          low_top_of_page_bid == o.low_top_of_page_bid &&
          high_top_of_page_bid == o.high_top_of_page_bid &&
          words_count == o.words_count &&
          detected_language == o.detected_language &&
          search_volume_trend == o.search_volume_trend &&
          serp_item_types == o.serp_item_types &&
          serp_results_count == o.serp_results_count &&
          monthly_searches == o.monthly_searches &&
          last_updated_at == o.last_updated_at &&
          depth == o.depth &&
          related_keywords == o.related_keywords
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [keyword, search_volume, cpc, competition, competition_level, keyword_difficulty, search_intent, search_intent_alternatives, low_top_of_page_bid, high_top_of_page_bid, words_count, detected_language, search_volume_trend, serp_item_types, serp_results_count, monthly_searches, last_updated_at, depth, related_keywords].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Unifapi.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
