=begin
#UnifAPI

#Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.

The version of the OpenAPI document: 0.0.1
Contact: support@unifapi.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module Unifapi
  class YouTubeVideo
    attr_accessor :id

    attr_accessor :title

    attr_accessor :description

    attr_accessor :channel_id

    attr_accessor :author

    attr_accessor :duration_seconds

    attr_accessor :view_count

    attr_accessor :keywords

    attr_accessor :thumbnail_url

    attr_accessor :is_live

    attr_accessor :is_private

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'title' => :'title',
        :'description' => :'description',
        :'channel_id' => :'channel_id',
        :'author' => :'author',
        :'duration_seconds' => :'duration_seconds',
        :'view_count' => :'view_count',
        :'keywords' => :'keywords',
        :'thumbnail_url' => :'thumbnail_url',
        :'is_live' => :'is_live',
        :'is_private' => :'is_private'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'title' => :'String',
        :'description' => :'String',
        :'channel_id' => :'String',
        :'author' => :'String',
        :'duration_seconds' => :'Float',
        :'view_count' => :'Float',
        :'keywords' => :'Array<String>',
        :'thumbnail_url' => :'String',
        :'is_live' => :'Boolean',
        :'is_private' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Unifapi::YouTubeVideo` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Unifapi::YouTubeVideo`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      else
        self.title = nil
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      else
        self.description = nil
      end

      if attributes.key?(:'channel_id')
        self.channel_id = attributes[:'channel_id']
      else
        self.channel_id = nil
      end

      if attributes.key?(:'author')
        self.author = attributes[:'author']
      else
        self.author = nil
      end

      if attributes.key?(:'duration_seconds')
        self.duration_seconds = attributes[:'duration_seconds']
      else
        self.duration_seconds = nil
      end

      if attributes.key?(:'view_count')
        self.view_count = attributes[:'view_count']
      else
        self.view_count = nil
      end

      if attributes.key?(:'keywords')
        if (value = attributes[:'keywords']).is_a?(Array)
          self.keywords = value
        end
      else
        self.keywords = nil
      end

      if attributes.key?(:'thumbnail_url')
        self.thumbnail_url = attributes[:'thumbnail_url']
      else
        self.thumbnail_url = nil
      end

      if attributes.key?(:'is_live')
        self.is_live = attributes[:'is_live']
      else
        self.is_live = nil
      end

      if attributes.key?(:'is_private')
        self.is_private = attributes[:'is_private']
      else
        self.is_private = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @id.to_s.length < 1
        invalid_properties.push('invalid value for "id", the character length must be great than or equal to 1.')
      end

      if @title.nil?
        invalid_properties.push('invalid value for "title", title cannot be nil.')
      end

      if @description.nil?
        invalid_properties.push('invalid value for "description", description cannot be nil.')
      end

      if @channel_id.nil?
        invalid_properties.push('invalid value for "channel_id", channel_id cannot be nil.')
      end

      if @author.nil?
        invalid_properties.push('invalid value for "author", author cannot be nil.')
      end

      if @duration_seconds.nil?
        invalid_properties.push('invalid value for "duration_seconds", duration_seconds cannot be nil.')
      end

      if @view_count.nil?
        invalid_properties.push('invalid value for "view_count", view_count cannot be nil.')
      end

      if @keywords.nil?
        invalid_properties.push('invalid value for "keywords", keywords cannot be nil.')
      end

      if @thumbnail_url.nil?
        invalid_properties.push('invalid value for "thumbnail_url", thumbnail_url cannot be nil.')
      end

      if @is_live.nil?
        invalid_properties.push('invalid value for "is_live", is_live cannot be nil.')
      end

      if @is_private.nil?
        invalid_properties.push('invalid value for "is_private", is_private cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @id.to_s.length < 1
      return false if @title.nil?
      return false if @description.nil?
      return false if @channel_id.nil?
      return false if @author.nil?
      return false if @duration_seconds.nil?
      return false if @view_count.nil?
      return false if @keywords.nil?
      return false if @thumbnail_url.nil?
      return false if @is_live.nil?
      return false if @is_private.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      if id.to_s.length < 1
        fail ArgumentError, 'invalid value for "id", the character length must be great than or equal to 1.'
      end

      @id = id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          title == o.title &&
          description == o.description &&
          channel_id == o.channel_id &&
          author == o.author &&
          duration_seconds == o.duration_seconds &&
          view_count == o.view_count &&
          keywords == o.keywords &&
          thumbnail_url == o.thumbnail_url &&
          is_live == o.is_live &&
          is_private == o.is_private
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, title, description, channel_id, author, duration_seconds, view_count, keywords, thumbnail_url, is_live, is_private].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Unifapi.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
