=begin
#UnifAPI

#Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.

The version of the OpenAPI document: 0.0.1
Contact: support@unifapi.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Unifapi::HackerNewsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'HackerNewsApi' do
  before do
    # run before each test
    @api_instance = Unifapi::HackerNewsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of HackerNewsApi' do
    it 'should create an instance of HackerNewsApi' do
      expect(@api_instance).to be_instance_of(Unifapi::HackerNewsApi)
    end
  end

  # unit tests for hacker_news_items_id_get
  # Get Hacker News item by ID
  # Fetch a single Hacker News item. Stories, comments, jobs, polls, and poll options share the same item shape.
  # @param id Hacker News item id.
  # @param [Hash] opts the optional parameters
  # @return [HackerNewsItemsIdGet200Response]
  describe 'hacker_news_items_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for hacker_news_max_item_get
  # Get largest Hacker News item ID
  # Returns the current largest Hacker News item id.
  # @param [Hash] opts the optional parameters
  # @return [HackerNewsMaxItemGet200Response]
  describe 'hacker_news_max_item_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for hacker_news_stories_feed_get
  # List Hacker News story IDs
  # List Hacker News story ids from a named feed. Use &#x60;/hacker-news/items/{id}&#x60; to fetch item details.
  # @param feed Story feed: top, new, best, ask, show, or jobs.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor Zero-based offset cursor returned as &#x60;next_cursor&#x60;.
  # @option opts [Integer] :limit 
  # @return [HackerNewsStoriesFeedGet200Response]
  describe 'hacker_news_stories_feed_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for hacker_news_stories_feed_items_get
  # List Hacker News story items
  # Fetch item details from a named Hacker News story feed in one operation. Use this when an agent needs readable story titles, URLs, scores, authors, or comment counts.
  # @param feed Story feed: top, new, best, ask, show, or jobs.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor Zero-based offset cursor returned as &#x60;next_cursor&#x60;.
  # @option opts [Integer] :limit 
  # @return [HackerNewsStoriesFeedItemsGet200Response]
  describe 'hacker_news_stories_feed_items_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for hacker_news_updates_get
  # Get changed Hacker News items and profiles
  # Returns recently changed Hacker News item ids and user profile ids.
  # @param [Hash] opts the optional parameters
  # @return [HackerNewsUpdatesGet200Response]
  describe 'hacker_news_updates_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for hacker_news_users_id_get
  # Get Hacker News user by ID
  # Fetch a public Hacker News user profile by case-sensitive username.
  # @param id Case-sensitive Hacker News username.
  # @param [Hash] opts the optional parameters
  # @return [HackerNewsUsersIdGet200Response]
  describe 'hacker_news_users_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
