=begin
#UnifAPI

#Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.

The version of the OpenAPI document: 0.0.1
Contact: support@unifapi.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Unifapi::HotelsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'HotelsApi' do
  before do
    # run before each test
    @api_instance = Unifapi::HotelsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of HotelsApi' do
    it 'should create an instance of HotelsApi' do
      expect(@api_instance).to be_instance_of(Unifapi::HotelsApi)
    end
  end

  # unit tests for hotels_info_post
  # Get Hotels detail
  # Run one live Hotels detail lookup for a hotel id from /hotels/search and receive the full profile, including class rating, address, phone, description, guest reviews, images, and prices.
  # @param [Hash] opts the optional parameters
  # @option opts [HotelInfoRequest] :hotel_info_request 
  # @return [HotelsInfoPost200Response]
  describe 'hotels_info_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for hotels_search_post
  # Search Hotels
  # Run one live Hotels search and receive ranked hotel listings for a location and stay dates, including hotel id, class rating, guest reviews, and nightly prices. Pass a hotel id to /hotels/info for full details.
  # @param [Hash] opts the optional parameters
  # @option opts [HotelSearchRequest] :hotel_search_request 
  # @return [HotelsSearchPost200Response]
  describe 'hotels_search_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
