=begin
#UnifAPI

#Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.

The version of the OpenAPI document: 0.0.1
Contact: support@unifapi.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Unifapi::LinkedinApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LinkedinApi' do
  before do
    # run before each test
    @api_instance = Unifapi::LinkedinApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LinkedinApi' do
    it 'should create an instance of LinkedinApi' do
      expect(@api_instance).to be_instance_of(Unifapi::LinkedinApi)
    end
  end

  # unit tests for linkedin_ads_id_get
  # Get a LinkedIn Ad Library entry by ID
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [LinkedinAdsIdGet200Response]
  describe 'linkedin_ads_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_companies_slug_affiliated_get
  # List a LinkedIn company&#39;s affiliated pages
  # @param slug 
  # @param [Hash] opts the optional parameters
  # @return [LinkedinCompaniesSlugAffiliatedGet200Response]
  describe 'linkedin_companies_slug_affiliated_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_companies_slug_get
  # Get a LinkedIn company profile by URL slug
  # @param slug LinkedIn URL slug (universal_name), e.g. &#x60;microsoft&#x60;
  # @param [Hash] opts the optional parameters
  # @return [LinkedinCompaniesSlugGet200Response]
  describe 'linkedin_companies_slug_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_companies_slug_job_count_get
  # Get the number of active jobs at a LinkedIn company
  # @param slug 
  # @param [Hash] opts the optional parameters
  # @return [LinkedinCompaniesSlugJobCountGet200Response]
  describe 'linkedin_companies_slug_job_count_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_companies_slug_jobs_get
  # List active job postings at a LinkedIn company
  # @param slug 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @return [LinkedinCompaniesSlugJobsGet200Response]
  describe 'linkedin_companies_slug_jobs_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_companies_slug_member_insights_get
  # Get a LinkedIn company&#39;s aggregated member insights
  # @param slug 
  # @param [Hash] opts the optional parameters
  # @return [LinkedinCompaniesSlugMemberInsightsGet200Response]
  describe 'linkedin_companies_slug_member_insights_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_companies_slug_people_get
  # List employees of a LinkedIn company
  # @param slug 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @return [LinkedinCompaniesSlugPeopleGet200Response]
  describe 'linkedin_companies_slug_people_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_companies_slug_posts_get
  # List posts published by a LinkedIn company page
  # @param slug 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @return [LinkedinCompaniesSlugPostsGet200Response]
  describe 'linkedin_companies_slug_posts_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_groups_id_get
  # Get a LinkedIn group by ID
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [LinkedinGroupsIdGet200Response]
  describe 'linkedin_groups_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_groups_id_posts_get
  # List posts in a LinkedIn group
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @return [LinkedinCompaniesSlugPostsGet200Response]
  describe 'linkedin_groups_id_posts_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_jobs_id_get
  # Get a LinkedIn job posting by ID
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include_skills 
  # @return [LinkedinJobsIdGet200Response]
  describe 'linkedin_jobs_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_posts_id_comments_comment_id_replies_get
  # List replies to a LinkedIn comment
  # &#x60;cursor&#x60; here is LinkedIn&#39;s &#x60;previous_replies_token&#x60;. On the first page, send no cursor — LinkedIn&#39;s source still expects the param, so the gateway passes &#x60;-&#x60; as the sentinel it documents.
  # @param id 
  # @param comment_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @return [LinkedinPostsIdCommentsCommentIdRepliesGet200Response]
  describe 'linkedin_posts_id_comments_comment_id_replies_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_posts_id_comments_get
  # List top-level comments on a LinkedIn post
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @return [LinkedinPostsIdCommentsCommentIdRepliesGet200Response]
  describe 'linkedin_posts_id_comments_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_posts_id_get
  # Get a LinkedIn post by ID
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [LinkedinPostsIdGet200Response]
  describe 'linkedin_posts_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_posts_id_reactions_get
  # List users who reacted to a LinkedIn post
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @option opts [String] :type Filter by reaction type. &#x60;all&#x60; returns every reaction (default).
  # @return [LinkedinCompaniesSlugPeopleGet200Response]
  describe 'linkedin_posts_id_reactions_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_posts_id_reposts_get
  # List reposts of a LinkedIn post
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @return [LinkedinCompaniesSlugPostsGet200Response]
  describe 'linkedin_posts_id_reposts_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_search_ads_get
  # Search the LinkedIn Ad Library
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @option opts [String] :keyword 
  # @option opts [String] :advertiser_name 
  # @option opts [String] :country ISO-3166-1 alpha-2 code, e.g. &#x60;US&#x60;
  # @option opts [String] :date 
  # @return [LinkedinSearchAdsGet200Response]
  describe 'linkedin_search_ads_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_search_industries_get
  # Resolve a free-text industry name to LinkedIn industry IDs
  # @param keyword 
  # @param [Hash] opts the optional parameters
  # @return [LinkedinSearchIndustriesGet200Response]
  describe 'linkedin_search_industries_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_search_jobs_get
  # Search LinkedIn jobs by keyword and filters
  # @param keyword Free-text search query
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @option opts [String] :sort_by 
  # @option opts [String] :date_posted 
  # @option opts [String] :geocode 
  # @option opts [String] :company 
  # @option opts [String] :experience_level 
  # @option opts [String] :remote 
  # @option opts [String] :job_type 
  # @option opts [String] :easy_apply 
  # @option opts [String] :has_verifications 
  # @option opts [String] :under_10_applicants 
  # @option opts [String] :fair_chance_employer 
  # @return [LinkedinCompaniesSlugJobsGet200Response]
  describe 'linkedin_search_jobs_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_search_locations_get
  # Resolve a free-text location into LinkedIn geocode tokens
  # @param keyword 
  # @param [Hash] opts the optional parameters
  # @return [LinkedinSearchLocationsGet200Response]
  describe 'linkedin_search_locations_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_search_people_get
  # Search LinkedIn people by name, title, company, etc.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @option opts [String] :name 
  # @option opts [String] :first_name 
  # @option opts [String] :last_name 
  # @option opts [String] :title 
  # @option opts [String] :company 
  # @option opts [String] :school 
  # @option opts [String] :geocode_location 
  # @option opts [String] :current_company 
  # @option opts [String] :profile_language 
  # @option opts [String] :industry 
  # @option opts [String] :service_category 
  # @return [LinkedinCompaniesSlugPeopleGet200Response]
  describe 'linkedin_search_people_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_search_posts_get
  # Search LinkedIn posts by keyword
  # @param keyword 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @option opts [String] :date_posted 
  # @option opts [String] :sort_by 
  # @option opts [String] :from_member 
  # @option opts [String] :from_company 
  # @option opts [String] :content_type 
  # @return [LinkedinSearchPostsGet200Response]
  describe 'linkedin_search_posts_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_search_schools_get
  # Search LinkedIn schools by keyword
  # @param keyword 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @return [LinkedinSearchSchoolsGet200Response]
  describe 'linkedin_search_schools_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_users_username_about_get
  # Get a LinkedIn profile&#39;s &#39;about&#39; metadata
  # @param username 
  # @param [Hash] opts the optional parameters
  # @return [LinkedinUsersUsernameAboutGet200Response]
  describe 'linkedin_users_username_about_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_users_username_certifications_get
  # List a LinkedIn user&#39;s certifications
  # @param username 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @return [LinkedinUsersUsernameCertificationsGet200Response]
  describe 'linkedin_users_username_certifications_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_users_username_comments_get
  # List comments authored by a LinkedIn user
  # @param username 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @return [LinkedinUsersUsernameCommentsGet200Response]
  describe 'linkedin_users_username_comments_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_users_username_contact_get
  # Get a LinkedIn user&#39;s public contact info
  # Returns the contact block (websites, phone numbers, twitter handles, address, wechat) the user has chosen to publish on LinkedIn.
  # @param username 
  # @param [Hash] opts the optional parameters
  # @return [LinkedinUsersUsernameContactGet200Response]
  describe 'linkedin_users_username_contact_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_users_username_educations_get
  # List a LinkedIn user&#39;s education
  # @param username 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @return [LinkedinUsersUsernameEducationsGet200Response]
  describe 'linkedin_users_username_educations_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_users_username_experience_get
  # List a LinkedIn user&#39;s work experience
  # @param username 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @return [LinkedinUsersUsernameExperienceGet200Response]
  describe 'linkedin_users_username_experience_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_users_username_follower_count_get
  # Get a LinkedIn user&#39;s follower &amp; connection counts
  # @param username 
  # @param [Hash] opts the optional parameters
  # @return [LinkedinUsersUsernameFollowerCountGet200Response]
  describe 'linkedin_users_username_follower_count_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_users_username_get
  # Get a LinkedIn user profile by URL slug
  # Returns the canonical LinkedIn profile for the given URL slug (&#x60;public_identifier&#x60;). Returns 404 not_found if no such user exists.
  # @param username LinkedIn URL slug, e.g. &#x60;williamhgates&#x60;
  # @param [Hash] opts the optional parameters
  # @return [LinkedinUsersUsernameGet200Response]
  describe 'linkedin_users_username_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_users_username_honors_get
  # List a LinkedIn user&#39;s honors and awards
  # @param username 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @return [LinkedinUsersUsernameHonorsGet200Response]
  describe 'linkedin_users_username_honors_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_users_username_images_get
  # List image posts authored by a LinkedIn user
  # @param username 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @return [LinkedinUsersUsernameImagesGet200Response]
  describe 'linkedin_users_username_images_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_users_username_interests_companies_get
  # List companies a LinkedIn user follows
  # @param username 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @return [LinkedinUsersUsernameInterestsCompaniesGet200Response]
  describe 'linkedin_users_username_interests_companies_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_users_username_interests_groups_get
  # List LinkedIn groups a user follows
  # @param username 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @return [LinkedinUsersUsernameInterestsGroupsGet200Response]
  describe 'linkedin_users_username_interests_groups_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_users_username_posts_get
  # List posts authored by a LinkedIn user
  # @param username 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @return [LinkedinCompaniesSlugPostsGet200Response]
  describe 'linkedin_users_username_posts_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_users_username_publications_get
  # List a LinkedIn user&#39;s publications
  # @param username 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @return [LinkedinUsersUsernamePublicationsGet200Response]
  describe 'linkedin_users_username_publications_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_users_username_reactions_get
  # List reactions a LinkedIn user has placed on posts
  # @param username 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @return [LinkedinUsersUsernameReactionsGet200Response]
  describe 'linkedin_users_username_reactions_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_users_username_recommendations_get
  # List recommendations written for a LinkedIn user
  # @param username 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @return [LinkedinUsersUsernameRecommendationsGet200Response]
  describe 'linkedin_users_username_recommendations_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_users_username_skills_get
  # List a LinkedIn user&#39;s skills
  # @param username 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @return [LinkedinUsersUsernameSkillsGet200Response]
  describe 'linkedin_users_username_skills_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_users_username_videos_get
  # List video posts authored by a LinkedIn user
  # @param username 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @return [LinkedinUsersUsernameVideosGet200Response]
  describe 'linkedin_users_username_videos_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for linkedin_users_username_volunteers_get
  # List a LinkedIn user&#39;s volunteer experience
  # @param username 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @return [LinkedinUsersUsernameVolunteersGet200Response]
  describe 'linkedin_users_username_volunteers_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
