=begin
#UnifAPI

#Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.

The version of the OpenAPI document: 0.0.1
Contact: support@unifapi.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Unifapi::LocalApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LocalApi' do
  before do
    # run before each test
    @api_instance = Unifapi::LocalApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LocalApi' do
    it 'should create an instance of LocalApi' do
      expect(@api_instance).to be_instance_of(Unifapi::LocalApi)
    end
  end

  # unit tests for local_search_post
  # Search Local Finder
  # Run one live Local Finder search — the expanded local-pack listing — and receive ranked local places for a query, including title, address, rating, phone, and booking links.
  # @param [Hash] opts the optional parameters
  # @option opts [LocalFinderRequest] :local_finder_request 
  # @return [LocalSearchPost200Response]
  describe 'local_search_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
