=begin
#UnifAPI

#Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.

The version of the OpenAPI document: 0.0.1
Contact: support@unifapi.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Unifapi::MapsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MapsApi' do
  before do
    # run before each test
    @api_instance = Unifapi::MapsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MapsApi' do
    it 'should create an instance of MapsApi' do
      expect(@api_instance).to be_instance_of(Unifapi::MapsApi)
    end
  end

  # unit tests for maps_search_post
  # Search Maps
  # Run one live Maps search and receive ranked local business listings for a query, including title, address, rating, category, phone, coordinates, and place id.
  # @param [Hash] opts the optional parameters
  # @option opts [MapsSearchRequest] :maps_search_request 
  # @return [MapsSearchPost200Response]
  describe 'maps_search_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
