=begin
#UnifAPI

#Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.

The version of the OpenAPI document: 0.0.1
Contact: support@unifapi.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Unifapi::SeoApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SeoApi' do
  before do
    # run before each test
    @api_instance = Unifapi::SeoApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SeoApi' do
    it 'should create an instance of SeoApi' do
      expect(@api_instance).to be_instance_of(Unifapi::SeoApi)
    end
  end

  # unit tests for seo_backlinks_anchors_post
  # Get anchor texts used in backlinks to a target
  # Return the anchor texts used in backlinks pointing to a target, each with backlink, referring-domain, and spam-score counters, to analyze anchor-text distribution.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoBacklinksAnchorsRequest] :seo_backlinks_anchors_request 
  # @return [SeoBacklinksAnchorsPost200Response]
  describe 'seo_backlinks_anchors_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_backlinks_bulk_backlinks_post
  # Count backlinks for many targets
  # Return the total number of backlinks pointing to up to 1000 domains, subdomains, or pages at once, for bulk link-volume comparison.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoBacklinksBulkBacklinksRequest] :seo_backlinks_bulk_backlinks_request 
  # @return [SeoBacklinksBulkBacklinksPost200Response]
  describe 'seo_backlinks_bulk_backlinks_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_backlinks_bulk_new_lost_backlinks_post
  # Count new and lost backlinks for many targets
  # Return the number of new and lost backlinks for up to 1000 domains, subdomains, or pages since a given date, for bulk link-velocity tracking.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoBacklinksBulkNewLostBacklinksRequest] :seo_backlinks_bulk_new_lost_backlinks_request 
  # @return [SeoBacklinksBulkNewLostBacklinksPost200Response]
  describe 'seo_backlinks_bulk_new_lost_backlinks_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_backlinks_bulk_new_lost_referring_domains_post
  # Count new and lost referring domains for many targets
  # Return the number of new and lost referring domains for up to 1000 domains, subdomains, or pages since a given date, for bulk referring-domain velocity tracking.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoBacklinksBulkNewLostReferringDomainsRequest] :seo_backlinks_bulk_new_lost_referring_domains_request 
  # @return [SeoBacklinksBulkNewLostReferringDomainsPost200Response]
  describe 'seo_backlinks_bulk_new_lost_referring_domains_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_backlinks_bulk_pages_summary_post
  # Summarize backlinks for many pages at once
  # Return backlink summaries for up to 1000 pages, domains, or subdomains at once, each with backlink, referring-domain, and spam-score counters, for bulk link-profile comparison.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoBacklinksBulkPagesSummaryRequest] :seo_backlinks_bulk_pages_summary_request 
  # @return [SeoBacklinksBulkPagesSummaryPost200Response]
  describe 'seo_backlinks_bulk_pages_summary_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_backlinks_bulk_ranks_post
  # Get backlink ranks for many targets
  # Return the backlink rank score (0-1000, similar to PageRank) for up to 1000 domains, subdomains, or pages at once, for quick bulk authority comparison.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoBacklinksBulkRanksRequest] :seo_backlinks_bulk_ranks_request 
  # @return [SeoBacklinksBulkRanksPost200Response]
  describe 'seo_backlinks_bulk_ranks_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_backlinks_bulk_referring_domains_post
  # Count referring domains for many targets
  # Return the number of referring domains pointing to up to 1000 domains, subdomains, or pages at once, for bulk referring-domain comparison.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoBacklinksBulkReferringDomainsRequest] :seo_backlinks_bulk_referring_domains_request 
  # @return [SeoBacklinksBulkReferringDomainsPost200Response]
  describe 'seo_backlinks_bulk_referring_domains_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_backlinks_bulk_spam_score_post
  # Get spam scores for many targets
  # Return the DataForSEO spam score (0-100) for up to 1000 domains, subdomains, or pages at once, to flag risky backlink targets in bulk.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoBacklinksBulkSpamScoreRequest] :seo_backlinks_bulk_spam_score_request 
  # @return [SeoBacklinksBulkSpamScorePost200Response]
  describe 'seo_backlinks_bulk_spam_score_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_backlinks_competitors_post
  # Find competitors by shared referring domains
  # Return the domains that share referring domains with a target, ranked by the number of shared referring domains, to discover competitors in the same backlink neighborhood.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoBacklinksCompetitorsRequest] :seo_backlinks_competitors_request 
  # @return [SeoBacklinksCompetitorsPost200Response]
  describe 'seo_backlinks_competitors_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_backlinks_domain_intersection_post
  # Find domains linking to multiple targets
  # Return the domains that link to a set of targets, with per-target backlink metrics. Useful for a link-gap analysis: domains linking to competitors but not to your site.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoBacklinksDomainIntersectionRequest] :seo_backlinks_domain_intersection_request 
  # @return [SeoBacklinksDomainIntersectionPost200Response]
  describe 'seo_backlinks_domain_intersection_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_backlinks_domain_pages_post
  # List target pages ranked by backlinks
  # Return the pages of a target domain or subdomain that receive backlinks, each with crawl data and backlink counters, to find the most-linked pages of a site.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoBacklinksDomainPagesRequest] :seo_backlinks_domain_pages_request 
  # @return [SeoBacklinksDomainPagesPost200Response]
  describe 'seo_backlinks_domain_pages_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_backlinks_domain_pages_summary_post
  # Summarize backlinks for each page of a target
  # Return per-page backlink summaries for a target domain or subdomain, each page with backlink, referring-domain, and spam-score counters, to find the most-linked pages.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoBacklinksDomainPagesSummaryRequest] :seo_backlinks_domain_pages_summary_request 
  # @return [SeoBacklinksDomainPagesSummaryPost200Response]
  describe 'seo_backlinks_domain_pages_summary_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_backlinks_history_post
  # Get historical backlink metrics for a target
  # Return a monthly time series of a target&#39;s backlink profile since 2019 — backlinks, referring domains, new/lost counts, and rank — for link-growth trend analysis.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoBacklinksHistoryRequest] :seo_backlinks_history_request 
  # @return [SeoBacklinksHistoryPost200Response]
  describe 'seo_backlinks_history_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_backlinks_list_post
  # List individual backlinks pointing to a target
  # Return the individual backlinks pointing to a target domain, subdomain, or page, each with the referring URL, anchor, dofollow flag, rank, and spam score, for detailed link auditing.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoBacklinksListRequest] :seo_backlinks_list_request 
  # @return [SeoBacklinksListPost200Response]
  describe 'seo_backlinks_list_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_backlinks_page_intersection_post
  # Find pages linking to multiple targets
  # Return the referring pages that link to a set of targets, with the backlinks to each target. Useful for finding pages that link to your competitors but not to your site.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoBacklinksPageIntersectionRequest] :seo_backlinks_page_intersection_request 
  # @return [SeoBacklinksPageIntersectionPost200Response]
  describe 'seo_backlinks_page_intersection_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_backlinks_referring_domains_post
  # List referring domains pointing to a target
  # Return the domains that link to a target domain, subdomain, or page, each with backlink, referring-domain, and spam-score counters for referring-domain analysis.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoReferringDomainsRequest] :seo_referring_domains_request 
  # @return [SeoBacklinksReferringDomainsPost200Response]
  describe 'seo_backlinks_referring_domains_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_backlinks_referring_networks_post
  # List referring IP networks pointing to a target
  # Return the IP addresses or subnets that host pages linking to a target, each with backlink and referring-domain counters, to assess referring-network diversity.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoBacklinksReferringNetworksRequest] :seo_backlinks_referring_networks_request 
  # @return [SeoBacklinksReferringNetworksPost200Response]
  describe 'seo_backlinks_referring_networks_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_backlinks_summary_post
  # Get the backlink profile summary for a target
  # Return an overview of a target&#39;s backlink profile: total backlinks, referring domains/pages/IPs, rank, spam score, and broken-link counters, for a quick link-profile health check.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoBacklinksSummaryRequest] :seo_backlinks_summary_request 
  # @return [SeoBacklinksSummaryPost200Response]
  describe 'seo_backlinks_summary_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_backlinks_timeseries_new_lost_post
  # Get new and lost backlinks over time
  # Return a time series of new and lost backlinks and referring domains for a target, grouped by day, week, month, or year, for link-velocity analysis.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoBacklinksTimeseriesNewLostRequest] :seo_backlinks_timeseries_new_lost_request 
  # @return [SeoBacklinksTimeseriesNewLostPost200Response]
  describe 'seo_backlinks_timeseries_new_lost_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_backlinks_timeseries_post
  # Get backlink metrics over time
  # Return a time series of a target&#39;s backlink metrics grouped by day, week, month, or year between two dates, for tracking backlink and referring-domain trends.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoBacklinksTimeseriesRequest] :seo_backlinks_timeseries_request 
  # @return [SeoBacklinksTimeseriesPost200Response]
  describe 'seo_backlinks_timeseries_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_competitors_bulk_traffic_post
  # Estimate organic traffic for domains
  # Return the estimated monthly organic and paid search traffic for a list of domains, for quick competitor sizing and prospecting across many domains at once.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoBulkTrafficRequest] :seo_bulk_traffic_request 
  # @return [SeoCompetitorsBulkTrafficPost200Response]
  describe 'seo_competitors_bulk_traffic_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_competitors_domain_intersection_post
  # Find keywords two domains both rank for
  # Return the keywords for which two domains both rank, with each domain&#39;s position and URL, to find shared keywords or keyword gaps between competitors.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoDomainIntersectionRequest] :seo_domain_intersection_request 
  # @return [SeoCompetitorsDomainIntersectionPost200Response]
  describe 'seo_competitors_domain_intersection_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_competitors_domain_post
  # Find a domain&#39;s organic competitors
  # Return the domains that compete with a target domain in organic search, with shared-keyword counts and ranking/traffic metrics, for competitive landscape analysis.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoCompetitorsDomainRequest] :seo_competitors_domain_request 
  # @return [SeoCompetitorsDomainPost200Response]
  describe 'seo_competitors_domain_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_competitors_domain_rank_overview_post
  # Get a domain&#39;s ranking and traffic overview
  # Return the organic and paid ranking distribution and estimated traffic for a target domain, summarizing how many keywords it ranks for in each position bucket.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoDomainRankOverviewRequest] :seo_domain_rank_overview_request 
  # @return [SeoCompetitorsDomainRankOverviewPost200Response]
  describe 'seo_competitors_domain_rank_overview_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_competitors_historical_bulk_traffic_post
  # Estimate historical traffic for domains
  # Return a monthly estimated organic and paid traffic time series for a list of domains since 2019, for comparing competitor growth trajectories over time.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoHistoricalBulkTrafficRequest] :seo_historical_bulk_traffic_request 
  # @return [SeoCompetitorsHistoricalBulkTrafficPost200Response]
  describe 'seo_competitors_historical_bulk_traffic_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_competitors_historical_rank_overview_post
  # Get a domain&#39;s historical ranking overview
  # Return a monthly time series of a domain&#39;s organic and paid ranking distribution and estimated traffic since 2019, for trend and seasonality analysis.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoHistoricalRankOverviewRequest] :seo_historical_rank_overview_request 
  # @return [SeoCompetitorsHistoricalRankOverviewPost200Response]
  describe 'seo_competitors_historical_rank_overview_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_competitors_historical_serps_post
  # Get historical SERP snapshots for a keyword
  # Return historical snapshots of the SERP composition for a keyword since 2019, summarizing how many results and which SERP feature types appeared over time.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoHistoricalSerpsRequest] :seo_historical_serps_request 
  # @return [SeoCompetitorsHistoricalSerpsPost200Response]
  describe 'seo_competitors_historical_serps_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_competitors_page_intersection_post
  # Find keywords specific pages rank for
  # Return the keywords that a set of specific page URLs rank for, with each page&#39;s position, to analyze keyword overlap across competing pages or your own content.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoPageIntersectionRequest] :seo_page_intersection_request 
  # @return [SeoCompetitorsPageIntersectionPost200Response]
  describe 'seo_competitors_page_intersection_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_competitors_ranked_keywords_post
  # Find the keywords a domain ranks for
  # Return the keywords a target domain or page ranks for in organic search, each with search volume, difficulty, and the exact ranking position and URL, for competitor keyword research.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoRankedKeywordsRequest] :seo_ranked_keywords_request 
  # @return [SeoCompetitorsRankedKeywordsPost200Response]
  describe 'seo_competitors_ranked_keywords_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_competitors_relevant_pages_post
  # List a domain&#39;s top ranking pages
  # Return the pages of a target domain that drive the most organic search traffic, each with its ranking distribution and estimated traffic, for content gap and page-level analysis.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoRelevantPagesRequest] :seo_relevant_pages_request 
  # @return [SeoCompetitorsRelevantPagesPost200Response]
  describe 'seo_competitors_relevant_pages_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_competitors_serp_post
  # Find domains competing for keywords
  # Return the domains that rank for a set of seed keywords, ranked by visibility, with average position, estimated traffic, and the number of shared keywords, to discover SERP competitors.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoSerpCompetitorsRequest] :seo_serp_competitors_request 
  # @return [SeoCompetitorsSerpPost200Response]
  describe 'seo_competitors_serp_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_competitors_subdomains_post
  # List a domain&#39;s subdomains with traffic
  # Return the subdomains of a target domain, each with its organic ranking distribution and estimated traffic, to see which subdomains drive search visibility.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoSubdomainsRequest] :seo_subdomains_request 
  # @return [SeoCompetitorsSubdomainsPost200Response]
  describe 'seo_competitors_subdomains_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_keywords_autocomplete_post
  # Collect autocomplete keyword suggestions
  # Run one live autocomplete lookup for a seed query and receive the suggested searches the engine offers, with relevance scores — useful for SEO keyword discovery and content-gap research.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoKeywordAutocompleteRequest] :seo_keyword_autocomplete_request 
  # @return [SeoKeywordsAutocompletePost200Response]
  describe 'seo_keywords_autocomplete_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_keywords_difficulty_post
  # Score keyword difficulty
  # Return the keyword difficulty (0-100 chance of ranking in the top-10 organic results) for up to 1,000 keywords in one request, for prioritizing achievable SEO targets.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoKeywordDifficultyRequest] :seo_keyword_difficulty_request 
  # @return [SeoKeywordsDifficultyPost200Response]
  describe 'seo_keywords_difficulty_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_keywords_for_site_post
  # Find keywords a domain ranks for
  # Return the keywords a target domain is relevant for, each with search volume, CPC, competition, keyword difficulty, and search intent, for competitor and own-site keyword research.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoKeywordsForSiteRequest] :seo_keywords_for_site_request 
  # @return [SeoKeywordsForSitePost200Response]
  describe 'seo_keywords_for_site_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_keywords_history_post
  # Get historical keyword data
  # Return historical search volume and search ad metrics since 2019 for specified keywords, for trend and seasonality analysis.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoKeywordHistoryRequest] :seo_keyword_history_request 
  # @return [SeoKeywordsHistoryPost200Response]
  describe 'seo_keywords_history_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_keywords_ideas_post
  # Discover keyword ideas
  # Expand seed keywords into related search terms that fall into the same product or service categories, each with search volume, CPC, competition, keyword difficulty, and search intent for SEO and content research.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoKeywordIdeasRequest] :seo_keyword_ideas_request 
  # @return [SeoKeywordsIdeasPost200Response]
  describe 'seo_keywords_ideas_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_keywords_intent_post
  # Classify keyword search intent
  # Return the search intent (informational, navigational, commercial, or transactional) with probabilities for up to 1,000 keywords, for mapping keywords to the right content type.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoKeywordIntentRequest] :seo_keyword_intent_request 
  # @return [SeoKeywordsIntentPost200Response]
  describe 'seo_keywords_intent_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_keywords_overview_post
  # Look up keyword metrics
  # Return current SEO metrics for specified keywords, including search volume, CPC, competition, keyword difficulty, and search intent, for prioritizing keyword targets.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoKeywordOverviewRequest] :seo_keyword_overview_request 
  # @return [SeoKeywordsOverviewPost200Response]
  describe 'seo_keywords_overview_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_keywords_related_post
  # Find related keywords
  # Expand a seed keyword using the &#39;searches related to&#39; element, each with search volume, CPC, competition, keyword difficulty, and search intent for SEO and content research.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoRelatedKeywordsRequest] :seo_related_keywords_request 
  # @return [SeoKeywordsRelatedPost200Response]
  describe 'seo_keywords_related_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_keywords_suggestions_post
  # Find keyword suggestions
  # Expand a seed keyword into long-tail search queries that include it, each with search volume, CPC, competition, keyword difficulty, and search intent for SEO and content research.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoKeywordSuggestionsRequest] :seo_keyword_suggestions_request 
  # @return [SeoKeywordsSuggestionsPost200Response]
  describe 'seo_keywords_suggestions_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for seo_serp_post
  # Collect organic SERP SEO evidence
  # Run one live organic SERP check for SEO optimization evidence, including target visibility, competitor domains, rich SERP features, People Also Ask context, AI Overview presence, and optional pixel ranking data.
  # @param [Hash] opts the optional parameters
  # @option opts [SeoSerpRequest] :seo_serp_request 
  # @return [SeoSerpPost200Response]
  describe 'seo_serp_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
