=begin
#UnifAPI

#Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.

The version of the OpenAPI document: 0.0.1
Contact: support@unifapi.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Unifapi::ThreadsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ThreadsApi' do
  before do
    # run before each test
    @api_instance = Unifapi::ThreadsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ThreadsApi' do
    it 'should create an instance of ThreadsApi' do
      expect(@api_instance).to be_instance_of(Unifapi::ThreadsApi)
    end
  end

  # unit tests for threads_search_profiles_get
  # Search Threads users by keyword
  # @param q Search keyword.
  # @param [Hash] opts the optional parameters
  # @return [ThreadsSearchProfilesGet200Response]
  describe 'threads_search_profiles_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for threads_search_recent_get
  # Search recent Threads posts
  # @param q Search keyword.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @return [ThreadsSearchRecentGet200Response]
  describe 'threads_search_recent_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for threads_search_top_get
  # Search top Threads posts
  # @param q Search keyword.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @return [ThreadsSearchRecentGet200Response]
  describe 'threads_search_top_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for threads_users_username_get
  # Get a Threads user profile by username
  # @param username 
  # @param [Hash] opts the optional parameters
  # @return [ThreadsUsersUsernameGet200Response]
  describe 'threads_users_username_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for threads_users_username_posts_get
  # List Threads posts authored by a user
  # @param username 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @return [ThreadsSearchRecentGet200Response]
  describe 'threads_users_username_posts_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for threads_users_username_replies_get
  # List Threads replies authored by a user
  # @param username 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @return [ThreadsSearchRecentGet200Response]
  describe 'threads_users_username_replies_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for threads_users_username_reposts_get
  # List Threads reposts by a user
  # @param username 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @return [ThreadsSearchRecentGet200Response]
  describe 'threads_users_username_reposts_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
