=begin
#UnifAPI

#Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.

The version of the OpenAPI document: 0.0.1
Contact: support@unifapi.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Unifapi::SeoBacklinksStatusType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Unifapi::SeoBacklinksStatusType do
  let(:instance) { Unifapi::SeoBacklinksStatusType.new }

  describe 'test an instance of SeoBacklinksStatusType' do
    it 'should create an instance of SeoBacklinksStatusType' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Unifapi::SeoBacklinksStatusType)
    end
  end

end
